#ifndef __EVENT_PROTOCOL_H__
#define __EVENT_PROTOCOL_H__

namespace EventProtocol
{
	const int EVENT_UC_LOGIN_RESPONSE = 10;
	const int EVENT_UC_ENTER_PLATFORM_RESPONSE = 11;
	const int EVENT_UC_PAY_RESPONSE = 12;

	const int EVENT_CHAT_MSG = 100;
	const int EVENT_PRIVATE_CHAT = 101;
	
	const int EVENT_LISTTALK_LIST = 200;
	const int EVENT_LISTTALK_CONTENT = 201;
	const int EVENT_LISTTALK_TITLE = 202;

	const int EVENT_GUILD_MSG = 300;
	const int EVENT_GUILD_LIST = 301;
	const int EVENT_GUILD_MEMBER = 302;
	const int EVENT_GUILD_ENEMY = 303;
	const int EVENT_GUILD_FRIEND = 304;
	const int EVENT_GUILD_INFO = 305;

	const int EVENT_ALERT_MSG = 310;
	const int EVENT_CUE_MUMSG = 311;
	const int EVENT_CUE_RDMSG = 312;
	const int EVENT_HINT_WITH_BOARD = 313;
	const int EVENT_ROLL_CUE_MSG = 314;

	const int EVENT_PLAYER_INFO = 400;
	const int EVENT_PLAYEREQUIP_INFO = 401;
	const int EVENT_PAYERMONEY_INFO = 402;
	const int EVENT_EXPERIENCE_CHANGE = 403;

	const int EVENT_FRIEND_FRESH = 500;

	const int EVENT_TASK_CHANGE = 600;

	const int EVENT_GAME_MONEY_CHANGE = 700;

	const int EVENT_ITEM_CHANGE = 800;
	
	const int EVENT_ATTRIBUTE_CHANGE = 900;

	const int EVENT_AVATAR_CHANGE = 1000;

	const int EVENT_TASK_RECEIVED = 1100;

	const int EVENT_LOADING_RESOURCE = 1200;

	const int EVENT_CHART_LIST = 1300;

	const int EVENT_NET_NPC_SHOP = 1400;

	const int EVENT_MAIN_ROLE_RELIVE = 1501;

	const int EVENT_NET_LOAD_SHORTCUT = 1600;
	const int EVENT_NET_SKILL_CHANGE = 1601;
	const int EVENT_NET_LOTTERY_LIST = 1602;

	const int EVENT_GROUP_LIST_CHANGED = 1700;

	const int EVENT_MERGE_STEEL = 1800;
	const int EVENT_UPGRADE_EQUIP = 1801;
	const int EVENT_EXCHANGE_UPGRADE = 1802;
	const int EVENT_RERANDADD = 1803;

	const int EVENT_COUNT_DOWN = 1900;

	const int EVENT_FIRST_CHARGE = 2000;

	const int EVENT_AUTHENTICASTE_SUCC = 2200;

	const int EVENT_ADD_BAGSLOT=2300;

	const int EVENT_CREATECHARACTER=2400;

	const int EVENT_LOCAL_ALERT = 2500;

	const int EVENT_RELIVEVCOIN=2600;

	const int EVENT_GUIDE_TIP=2700;

	const int EVENT_CHOICE_CHAT=2800;
	
	const int EVENT_GET_SERVER_LIST=2900;
	const int EVENT_SEND_SERVERID_AND_SID=2901;
	const int EVENT_GET_AUTH=2902;

	const int EVENT_TAIYANG_CHANGE=3000;

	const int EVENT_PRIVATE_TIPS=3100;

	const int EVENT_START_LIEHUO=3200;

	const int EVENT_VERSION_RIGHT=3300;

	const int EVENT_CONNECT_SERVER_SUCCESS=3400;
	const int EVENT_CONNECT_SERVER_FAILED=3401;

	const int EVENT_BANYE_SWITCH=3500;
	const int EVENT_CHISHA_SWITCH=3501;

	const int EVENT_VERSION_CHECK_RESPONSE=3600;

	const int EVENT_CHECK_USER_EXIST=3700;

	const int EVENT_REGISTER_SUCCESS=3800;
	const int EVENT_REGISTER_FAILED=3801;

	const int EVENT_LOGIN_SUCCESS=3900;
	const int EVENT_LOGIN_FAILED=3901;

	const int EVENT_REGISTER_REMIND=4000;

	const int EVENT_GET_TRADE_NO=4001;

	const int EVENT_FINISH_ALIPAY=4002;

	const int EVENT_ITEMEXCHANGE_FAILED=4100;

	const int EVENT_EQUIPBETTER_CHANGE=4200;

	const int EVENT_CHANGE_HP=4400;
	const int EVENT_CHANGE_MP=4401;

	const int EVENT_CHANGE_LEVEL=4500;

	const int EVENT_DELETEROLE_SUCCESS=4600;

	const int EVENT_NPC_CLICK=4700;
	const int EVENT_PLAYER_CLICK = 4701;

	const int EVENT_TARGET_DISAPPEAR=4750;

	const int EVENT_ITEM_UPDDATA = 4800;
	const int EVENT_MAXHONOR_UPDDATA = 4801;
	const int EVENT_CURHONOR_UPDDATA = 4802;
	const int EVENT_ITEM_SPILT = 4803;
	const int EVENT_ITEM_SUCCESS = 4850;
	const int EVENT_ITEM_FAILED = 4851;

	const int EVENT_ITEM_CANCEL=4900;

	const int EVENT_TURNTO_HSHC=5000;  //魂石
	const int EVENT_TURNTO_BTJM=5001;  //摆摊
	const int EVENT_TURNTO_OTHERBTJM=5002; //他人摆摊界面
	const int EVENT_PUTIN_OVER=5003; //定价结束 
	const int EVENT_MARKETITEM_UPDATA=5004;//接受摆摊物品详细信息
	const int EVENT_TURNTO_BTJM_H=5005;  //摆摊
	const int EVENT_TURNTO_HSXQ=5006;  //魂石
	const int EVENT_SELECT_ITEM = 5007;	//查看他人装备

	const int EVENT_PUTIN_OVER_Life= 5050;
	const int EVENT_PUTIN_OVER_Seconds= 5051;

	const int EVENT_GET_SHOP_DATA=5100;
	const int EVENT_GET_REPO_DATA=5101;

	const int EVENT_SHOP_BUY_ITEM=5200;
	const int EVENT_SHOW_KEYBOARD=5201;
	//const int EVENT_MONEY_NOT_ENOUGH=5202;

	const int EVENT_PET_UPDDATA = 5300;
	const int EVENT_PET_GETEXP = 5301;
	const int EVENT_PET_LEVELUP = 5302;
	const int EVENT_PET_REMOVE = 5303;

	const int EVENT_BAGCELL_LEFT = 5400;
	const int EVENT_BAGCELL_RIGHT = 5401;
	const int EVENT_PETBAGCELL_LEFT = 5402;
	const int EVENT_PETBAGCELL_RIGHT = 5403;
	const int EVENT_PUTIN_UNLOCK = 5404;

	const int EVENT_TEAM_DECISION_AGREE = 5500;
	const int EVENT_TEAM_DECISION_REFUSE = 5501;
	const int EVENT_TEAM_LIST_UPDATE = 5502;
	const int EVENT_TEAM_OPERATION = 5503;


	const int EVENT_TRADE_SELF = 5600;
	const int EVENT_TRADE_OTHER = 5601;
	const int EVENT_TRADE_SELFLOCK = 5602;
	const int EVENT_TRADE_OTHERLOCK = 5603;
	const int EVENT_TRADE_SELFUNLOCK = 5604;
	const int EVENT_TRADE_OTHERUNLOCK = 5605;
	const int EVENT_TRADEITEM_INFO=5606;//接受交易物品详细信息
	const int EVENT_TRADEITEM_UPDATA=5607;//更新

	const int EVENT_FAST_KEY = 5650; //快捷键更新
	//mobai
	const int EVENT_UPDATE_WOSHIP_DATA=5700;

	//caishenchuangguan
	const int EVENT_UPDATE_EMIGRATED_DATA=5750;
	const int EVENT_UPDATE_EMIGRATED_MISSIONUP=5751;
	const int EVENT_UPDATE_EMIGRATED_ROUNDOVER=5752;
	const int EVENT_UPDATE_EMIGRATED_DATALIST=5753;

	//treasure hunt
	const int EVENT_UPDATE_TREASURE_LIST=5800;
	const int EVENT_UPDATE_HAPPINESS=5801;

	//spider
	const int EVENT_SPIDER_ITEM_CHANGE=5900;
	const int EVENT_SPIDER_ITEM_OVER=5901;

	//spider
	const int EVENT_HORSE_CHANGE=6000;
	const int EVENT_HORSE_ADD_EXP=6001;
	const int EVENT_HORSE_LEVEL_UP=6002;
	const int EVENT_HORSE_EQUIP_ADD_EXP=6003;
	const int EVENT_HORSE_EQUIP_LEVEL_UP=6004;
}

#endif//__EVENT_PROTOCOL_H__
