--
--	This file is auto-generated by LUA
--	Ceapon Inc.
--



--
--	for table : Error
--
Error = {
	Success = 0,
	Unknown = 1,
	Script = 2,
	NotImplemented = 3,
	Player_is_OffLine = 4,
	Name_Exist = 5,
	PasswardError = 6,
	AccountNotExist = 7,
	AccountIsFreeze = 8,
	InvalidParam = 10,
	InvalidEntity = 11,
	InvalidCate = 12,
	InvalidType = 13,
	InvalidItem = 14,
	InvalidMgr = 15,
	InvalidScene = 16,
	InvalidStaticID = 17,
	InvalidStaticData = 18,
	InvalidItemMgr = 19,
	NotEnoughCondition = 20,
	NotEnoughLevel = 22,
	NotEnoughScrap = 23,
	NotEnoughItem = 24,
	NotEnoughSoul = 25,
	NotEnoughPower = 27,
	NotEnoughScore = 28,
	NotEnoughRebornLevel = 29,
	NotEnoughEquivalent = 30,
	NotEnoughReq = 31,
	NotEnoughMoney = 32,
	NotEnoughGold = 33,
	NotEnoughDiamond = 34,
	NotEnoughReputation = 35,
	NotEnoughHonor = 36,
	NotEnoughBeauty = 37,
	NotEnoughIntergration = 38,
	NotEquip = 39,
	NotEnoughDay = 40,
	NotEnoughPetLvl = 41,
	NotEnoughStonePoint = 42,
	NotEnoughRebornReq = 43,
	NotEnoughXianyu = 808, -- 仙玉不足的错误码
	NotEnoughLingli = 888, -- 灵力不足的错误码
	NotOpenNewFunc = 44,
	NotLearnSkill = 45,
	NotEnoughOil = 46,
	AlreadyUsed = 49,
	StillInCD = 50,
	UpToLimit = 51,
	LevelMax = 52,
	AlreadyGet = 53,
	EventNotOver = 54,
	Has_No_Item_Remain = 55,
	GetGiftSuccess = 56,
	AlreadySet = 57,
	TimeIsOver = 58,
	CanNotRemove = 60,
	CanNotReplace = 61,
	CanNotSameItem = 62,
	CanNotSameFootLv = 63,
	Not_Match_Gender = 70,
	Not_Match_Class = 71,
	Not_Has_Monster = 72,
	Not_Match_CityMaster = 73,
	Max_FastKey = 75,
	InvalidGift = 76,
	Contains_Sensitive_Words = 80,
	Contains_Special_Words = 81,
	Contains_Whitespace_Words = 82,
	ThisIsYourself = 85,
	FeaturesNotYetOpen = 90,
	PlayerInStillInQueue = 91,
	You_have_be_kicked = 95,
	Not_enough_lvl_for_boss = 96,
	EError_CrossForbiddenClientMsg = 97,
	RoleTooMuch = 100,
	PetTooMuch = 101,
	DogTooMuch = 102,
	ItemTooMuch = 103,
	NotInGuild = 104,
	NotInTeam = 105,
	TargetPlayerNotOnLine = 106,
	HaveNoDog = 107,
	NotEnoughVipLevel = 108,
	NotEnoughCnt = 109,
	MarketisOpen = 110,
	MarketNotOpen = 111,
	MarketNoItem = 112,
	SelfMarket = 113,
	PetnotSleep = 120,
	PetnotDead = 121,
	PetnotOn = 122,
	PetCantImprison = 123,
	PetNeedLight = 124,
	NotHasAdvanceAttr = 125,
	NotHasBestAttr = 126,
	MaxAdvanceAttr = 127,
	NotEnoughPetCnt = 128,
	PlayerisDead = 130,
	PlayerisAlive = 131,
	ReviveNotAllow = 132,
	PlayerisOffLine = 133,
	PlayerNotAllowChat = 134,
	PlayerSpeakTooFast = 135,
	PlayerSpeakNothing = 136,
	PlayerHasNotEquipThisItem = 137,
	PlayerisOnline = 138,
	InvalidCDType = 140,
	CDhasCleaned = 141,
	CDhasLocked = 142,
	NoNeedCleanCD = 143,
	LimitRewardHasGot = 150,
	NoRewardToGet = 151,
	NeedRecharge = 160,
	MaxBagSolt = 161,
	Sale30sinterval = 162,
	time3sspan = 163,
	time30sspan = 164,
	time10sspan = 165,
	ThingsOverMax = 170,
	TitleHasOpen = 175,
	TitleHasClose = 176,
	HasNotTitle = 177,
	AlreadyHasTitle = 178,
	BoothUpTypeLimit = 179,
	HasNotOffExp = 180,
	HorseNotOpen = 181,					-- 坐骑没有开放
	HorseYetMaxLevel = 182,				-- 坐骑已到顶级
	HorseUpLevelExpIsFull = 183, 		-- 坐骑经验条已满
	HorseFoodTypeInvalid = 184,			-- 无效的坐骑培养类型
	HorseEquipNotOpen = 185,			-- 坐骑装备未开放
	HorseEquipYetMaxLevel = 186,		-- 坐骑装备已到顶级
	HorseEquipUpLevelExpIsFull = 187, 	-- 坐骑装备经验条已满
    CurrentStateCantMount = 188,        -- 当前状态下,不能上马
	HorseUpLevelExpIsNotFull = 189, 	-- 坐骑经验条未满
	HorseEquipUpLevelExpIsNotFull = 190,-- 坐骑装备经验条未满
	InvalidHorseEquip = 191,			-- 无效的坐骑装备
	
	NotSuchSlot = 200,
	Item_BagisFull = 204,
	Item_SuccessBagFull = 205,
	Item_AlreadyInlay = 215,
	Item_NoMatchClass = 216,
	Item_NoMatchGender = 217,
	Item_DestinationNotFound = 220,
	Item_CDLocked = 226,
	Item_NotEnoughSlot = 227,
	Item_PlayerTypeErr = 228,
	Item_MedicineCDLocked = 229,
	Item_CanNotSell = 230,
	Item_CanNotDelete = 231,
	Item_CanNotMerge = 232,
	Item_CanNotForge = 233,
	Item_CanNotModifSysTime = 234,
	Item_CanNotBuy = 235,
	Item_CanNotUseOnMainRole = 236,
	Item_CanNotUseOnSubRole = 237,
	Item_SubRoleLvlLarger = 238,
	Item_InheritSlotCntErr = 239,
	Item_InheritNotEnough = 240,
	Item_MaxLvl = 241,
	Item_VipNotEnough = 242,
	Item_CantDoIt = 243,
	Item_CantReplace = 244,
	Item_NotEnoughEndure = 245,
	Item_CanNotAbandon = 246,
	Item_CanNotTrade = 247,
	Item_CanNotBooth = 248,
	Item_CanNotUse = 249,
	Item_Same_Position = 250,
	Item_Player_BagisFull = 251,
	Item_Pet_BagisFull = 252,
	Item_Warhouse_BagisFull = 253,
	Item_Market_BagisFull = 254,
	Item_NPCBAG_BagisFull = 255,
	Item_UnlockReqNotEnough = 260,
	Item_NotEnoughEhanceLevel = 261,
	Item_MaxBornLevel = 262,
	Item_ExpJadeNotFull = 265,
	Item_NoNeedRepair = 266,
	ItemSuccess = 270,
	ItemFaild = 271,
	Item_Add = 280,
	Item_Remove = 281,
	Item_CantLuckyUp = 283,
	Item_NotFuMo = 284,     -- 装备未附魔
	Item_ToMaxFuMoEnhanceCount = 285, -- 已达到最大附魔次数
	HorseRideStateError = 288, -- 下马才能切换错误码
	InvalidQuestID = 500,
	InvalidQuestState = 501,
	CantRemoveQuest = 502,
	QuestGetEnoughItem = 510,
	ItemNotThisQuest = 511,
	NotInRegion = 401,
	TeamMemberNotNear = 410,
	TooManyTimes = 411,
	EntranceClosed = 412,
	Scene_Not_Allow = 413,
	Scene_Not_Finish = 414,
	Scene_Peace_Area = 415,
	Cannot_QuitTeaminIns = 416,
	Scene_Stop_Mine = 417,
	Item_Not_Belong_You = 420,
	FlyBootisDisable = 450,
	NotEnoughFlyBoot = 451,
	MarketNotAllowPlace = 460,
	Mobai_is_over_max = 1001,
	Mobai_expper_is_max = 1002,
	Mobai_expchoose_lower = 1003,
	Mobai_addcnt_max = 1004,
	Mobai_cnt_is_zero = 1005,
	Caishenchuangguan_is_over_max = 1010,
	Caishenchuangguan_is_gameover = 1011,
	Caishenchuangguan_meetcase = 1012,
	Caishenchuangguan_has_quest = 1013,
	Meinvhusong_is_over_max = 1020,
	Meinvhusong_no_girl = 1021,
	Meinvhusong_is_begin = 1022,
	Meinvhusong_someone_begin = 1023,
	TreasureLevel_not_Enough = 1030,
	TreasureReward_is_Get = 1031,
	Rich_not_guildboss = 1040,
	Rich_not_enoughmoney = 1041,
	Rich_error_scene = 1042,
	Rich_not_hasguild = 1043,
	Arena_refresh_buff_max = 1050,
	Arena_fight_max = 1051,
	Arena_fight_zero = 1052,
	Arena_buff_best = 1053,
	Day_Sign_has_signed = 1060,
	Day_Sign_not_already = 1061,
	Day_Sign_Only_Retroactive_This_Week = 1062,
	Not_Reach_Need_Time = 1071,
	Gcz_Not_Allow_Defend_in = 1080,
	Gcz_Not_Begin = 1081,
	Gcz_Kill_Most_Not_You = 1082,
	Gcz_No_City_Master = 1083,
	InvalidNPCFunction = 700,
	EventInactive = 701,
	EventIsactive = 702,
	NotEnoughInstancePassport = 703,
	err_guild_unknow = 901,
	err_guild_reapp = 902,
	err_guild_authority = 903,
	err_guild_noapp = 904,
	err_guild_hasguild = 905,
	err_guild_notenoughgold = 906,
	err_guild_nothis = 907,
	err_guild_noguild = 908,
	err_guild_factionerr = 909,
	err_guild_overfive = 910,
	err_guild_nameused = 911,
	err_guild_creating = 912,
	err_guild_NotMaster = 913,
	err_guild_NotEnoughItem = 914,
	err_guild_nothismember = 915,
	err_guild_nametoolong = 916,
	err_guild_kickself = 917,
	err_guild_sameplayer = 918,
	err_guild_maxMember = 919,
	err_guild_bosshascalled = 920,
	err_guild_noboss = 921,
	err_guild_notinCpship = 922,
	err_guild_unknowfightid = 923,
	err_guild_bosscallmax = 924,
	err_guild_bossfightMax = 925,
	err_guild_bossleveltoolow = 926,
	err_guild_todaymeetend = 927,
	err_guild_meetnotinvite = 928,
	err_guild_meetnotbegin = 929,
	err_guild_isreward = 930,
	err_guild_invalidNickname = 931,
	err_guild_invalidJob = 932,
	err_guild_NotCityMasterGuild = 933,
	err_guild_invitee_has_app = 934,
	err_guild_app_success = 935,
	err_guild_get_welfare_success = 936,
	err_guild_invalid_Member = 937,
	err_guild_app_max = 938,
	err_guild_shop_invalid_page = 939,
	err_guild_shop_notenough_contribution = 940,
	err_guild_cancel_apply_success = 941,
	err_guild_not_apply = 942,
	err_guild_in_leave_time = 943,
	err_guild_post_reset_forbid = 944,
	err_guild_money_increased = 945,
	err_guild_on_22_on_friday = 946,
	Master_Leave_Invalid = 950,
	NotEnoughtGuildContribution = 951,
	err_guild_explore_building_not_found = 952,
	err_guild_explore_time_not_enough = 953,
	err_guild_welfare_is_opened = 954,
	err_guild_welfare_not_open = 955,
	err_guild_welfare_obtained = 956,
	err_guild_building_level_not_satisfied = 957,
	err_guild_gcz_occupy_reward_no_guild = 958,
	TargetAgreeToJoinGuild = 959,
	Gift_error_begin = 1300,
	GiftCodeServerError = 1310,
	GiftCodeInvaild = 1311,
	GiftCodeHasUsed = 1312,
	TradeError = 600,
	TradeFailed = 601,
	TradeSuccess = 602,
	TradeNotAllow = 603,
	TradeHasLock = 604,
	TradeSelfLock = 605,
	TradeSelfUnLock = 606,
	TradeOtherUnLock = 607,
	TradeOtherLock = 608,
	Combat_Failed = 300,
	Combat_OutOfMana = 301,
	Combat_NotInRange = 302,
	Combat_InvalidSkill = 303,
	Combat_InCoolDown = 305,
	Combat_PlayerIsDaze = 306,
	Combat_Skill_duplicate = 310,
	Combat_Skill_LevelNotEnough = 311,
	Combat_Skill_Totem = 320,
	pe_succeed = 1100,
	pe_unknown = 1101,
	pe_not_pet = 1102,
	pe_not_player = 1103,
	pe_not_gold = 1104,
	pe_not_exp = 1105,
	pe_not_allow = 1106,
	pe_not_enoughlvl = 1107,
	pe_is_combat = 1108,
	pe_already_max_lvl = 1109,
	BoothDownSuccess = 1110,
	BoothUpSuccess = 1111,
	MarketSuccess = 1112,
	MarketCantNone = 1113,
	NotAdvanceAttr = 1114,
	EPetError_CantFindPet = 1115,
	EPetError_TargetErrorState = 1116,
	EPetError_SrcErrorState = 1117,
	EPetError_NotRebornLv = 1118,
	EPetError_NotGobbleupLv = 1119,
	EPetError_ToMaxRebornNum = 1120,
	EPetError_SamePetReborn = 1121,
	TeamIsYouself = 800,
	TeamOperationOverTime = 801,
	Player_GetNoTeam = 802,
	Player_GetTeam = 803,
	TeamMaxMember = 804,
	You_GetTeam = 805,
	Not_Team_Leader = 806,
	PlayerIsInPrison = 807,
	
	Must_In_Team = 1317,              -- 必须有队伍
    Not_Couple = 1318,                -- 没有结婚
    Not_Your_Couple = 1319,           -- 队友不是你的伴侣
    Couple_Dungeon_Need_Two = 1320,   -- 情侣副本必须2人
	
	
	
}


--
--	for table : Opcode
--
Opcode = {
	Op_Init = 0,
	Op_Unknow = 1,
	Op_Test = 5,
	Op_Client_Test = 6,
	Op_GM_Test = 7,
	Op_Quest = 100,
	Op_Loot = 101,
	Op_Upgrade = 102,
	Op_Activity = 103,
	Op_Guild = 104,
	Op_KillMonster = 105,
	Op_Trade = 106,
	Op_Item = 107,
	Op_Gift = 108,
	Op_Recharge = 109,
	Op_MarketSell = 110,
	Op_Mine = 111,
	Op_BuyBag = 201,
	Op_PetFeed = 202,
	Op_Revive = 203,
	Op_PetLvlup = 204,
	Op_PlayerLvlExp = 205,
	Op_PetDead = 206,
	Op_MonsterDead = 207,
	Op_PetReborn = 208,
	Op_PropUpdate = 210,
	Op_MoneyUpdate = 211,
	Op_GoldUpdate = 212,
	Op_CouponUpdate = 213,
	Op_HonorUpdate = 214,
	Op_UpgradeHonorLvl = 220,
	Op_OpenHonorLvl = 221,
	Op_AddSkill = 230,
	Op_SkillLvlup = 231,
	Op_EquipPutOnOff = 250,
	Op_EquipChanged = 251,
	Op_ImprisonPet = 260,
	Op_DogAttack = 261,
	Op_DogDefense = 262,
	Op_DogUpgrade = 263,
	Op_flyingScene = 270,
	Op_Reborn = 280,
	Op_CleanCDBegin = 301,
	Op_CleanCDEnd = 399,
	Op_Item_Update = 401,
	Op_Item_Merge = 402,
	Op_Item_Forge = 403,
	Op_Item_Split = 404,
	Op_Item_Upgrade = 405,
	Op_Item_Reborn = 406,
	Op_Item_Enhance = 407,
	Op_Item_Evaluate = 408,
	Op_Item_ClearItem = 409,
	Op_Item_StoneTrans = 410,
	Op_Item_MagicWeapon = 411,
	Op_Item_ChangeAttr = 412,
	Op_Item_Mount = 413,
	Op_Item_Inherit = 414,
	Op_Item_Polish = 415,
	Op_Item_PerfectEnhance = 416,
	Op_Item_SetPosition = 417,
	Op_Item_Create = 418,
	Op_Item_Delete = 419,
	Op_Item_UnlockSlot = 420,
	Op_Item_ChangeEnhance = 421,
	Op_Item_ChangeEvaluate = 422,
	Op_Item_ClearAttr = 423,
	Op_Item_WingEnhance = 424,
	Op_Item_FootUp = 426,
	Op_Item_ChangeFoot = 427,
	Op_Item_MagicQL = 430,
	Op_Item_SyncItemBase = 450,
	Op_Item_SyncItemData = 451,
	Op_Item_UseExpJade = 460,
	Op_Item_Repair = 465,
	Op_Item_Durable = 466,
	Op_Item_Pile = 467,
	Op_Item_FuMo = 470,         -- 附魔
	Op_Item_FuMoEnhance = 471,  -- 附魔强化
	Op_Item_HorsePeiYang = 472,         -- 坐骑培养
	Op_Item_HorseOneKeyPeiYang = 473,   -- 坐骑一键培养
	Op_Item_HorseJinJie = 474,          -- 坐骑进阶
	Op_Item_HorseEquipQiangHua = 475,   -- 坐骑装备强化
	Op_Item_HorseEquipJinJie = 476,     -- 坐骑装备进阶
    Op_Item_Ride = 477,                 -- 上下马
    Op_Itme_Ride_Approach = 478,        -- 上马助跑
    Op_Item_HorseSetAppearance = 479,   -- 坐骑外观切换
		
	Op_SellItem = 500,
	Op_BuyItem = 501,
	Op_UseItem = 502,
	Op_UseStone = 503,
	Op_AbandonItem = 504,
	Op_ItemBuyBack = 505,
	Op_AbandonItemDead = 506,
	Op_ShopBuyItemVcion = 507,
	Op_ShopBuyItemCoupon = 508,
	Op_ShopBuyItemScore = 509,
	Op_Activity_Begin = 800,
	Op_refresh_mobai = 801,
	Op_refresh_meinv = 802,
	Op_ActivityStateChange = 803,
	Op_fire = 810,
	Op_mobai = 811,
	Op_caishenchuangguan = 812,
	Op_Treasure_hunt = 813,
	Op_ProtectGirl = 814,
	Op_ArenaRefreshBuff = 815,
	Op_ArenaBuyFightCnt = 816,
	Op_liehuodongbuyling = 850,
	Op_liehuodonggonex = 851,
	Op_chdd_seed = 860,
	Op_chdd_bomb = 861,
	Op_mlsd = 862,
	Op_dyjj = 863,
	Op_slhd = 864,
	Op_wyzc = 865,
	Op_zszb = 866,
	Op_xmfb_call = 870,
	Op_xmfb_buy = 871,
	Op_SpiderThrowItem = 880,
	Op_buy_limit_time_gift = 3001,
	Op_Quest_Accept = 601,
	Op_Quest_Update = 602,
	Op_Quest_Finish = 603,
	Op_Quest_Remove = 604,
	Op_Quest_Submit = 605,
	Op_Quest_Enable = 606,
	Op_Quest_Init = 607,
	Op_Quest_Quick = 608,
	Op_NPC_Function = 609,
	Op_pet_pick_up = 4000,
	team_add_member = 5000,
	team_del_member = 5001,
	team_exit = 5002,
	team_set_leader = 5003,
}


--
--	for table : EntityProp
--
EntityProp = {
	ett_Base = 0,
	ett_Player = 1,
	ett_Role = 2,
	ett_NPC = 3,
	ett_MonsterGenerator = 4,
	ett_Monster = 5,
	ett_Skill = 6,
	ett_Destructible = 7,
	ett_Login = 8,
	ett_Item = 9,
	ett_Pet = 10,
	ett_Dog = 11,
	ett_Market = 12,
	ett_Max = 13,
	pk_Peace = 0,
	pk_Team = 1,
	pk_Guild = 2,
	pk_Red = 3,
	pk_Any = 4,
	pk_Faction = 5,
	pk_FactionMOnly = 6,
	pk_FactionPOnly = 7,
	pk_GuildMOnly = 8,
	pk_GuildPOnly = 9,
	pk_RedAndDog = 10,
	pk_RedOnly = 11,
	attr_bye_state = 0,
	attr_target_eid = 1,
	attr_last_attacker = 2,
	attr_owner_data = 3,
	attr_owner_type = 4,
	attr_pkmode = 5,
	attr_pkmode_backup = 6,
	attr_pkstate = 7,
	attr_mode = 8,
	attr_channel_id = 9,
	attr_device_id = 9,
	attr_platform_id = 15,
	attr_guild_id = 10,
	attr_team_id = 11,
	attr_faction_id = 12,
	attr_is_team_lead = 13,
	attr_owner_id = 14,
	attr_name_id = 15,
	attr_visiable = 35,
	attr_posion = 36,
	attr_is_safe = 37,
	attr_is_insand = 38,
	attr_area_id = 39,
	attr_effect_data = 50,
	attr_interval_attack = 60,
	attr_last_attack_ms = 61,
	attr_interval_move = 62,
	attr_move_speed = 63,
	attr_interval_track = 65,
	attr_gene_mitigateskill = 71,
	attr_gene_mitigate = 72,
	attr_gene_damage = 73,
	attr_gene_be_damage = 74,
	attr_gene_be_magic_damage = 75,
	attr_gene_damage_last_add = 76,
	attr_is_ex_load = 95,
	attr_is_offline = 96,
	attr_time_to_live = 97,
	attr_rmv_clean_id = 98,
	attr_invincible = 99,
	attr_script_start = 1000,
	attr_script_end = 9999,
	attr_exload = -1,
	attr_player_start = 100,
	attr_account = 100,
	attr_loadState = 101,
	attr_gender = 102,
	attr_bagslot = 103,
	attr_petbagslot = 104,
	attr_warehouseslot = 105,
	attr_npcbagslot = 106,
	attr_reborn = 110,
	attr_rebornrqeitem = 111,
	attr_lingliqeitem = 888,---灵力
	attr_pkvalue = 115,
	attr_identify = 116,
	attr_combat_data_num = 117,
	attr_combat_next_update = 118,
	attr_meritorious = 119,
	attr_instance_iid = 120,
	attr_safe_id = 121,
	attr_move_cnt = 131,
	attr_exp_next_update = 138,
	attr_exp_ex = 139,
	attr_equivalent = 140,
	attr_exp = 141,
	attr_money = 142,
	attr_gold = 143,
	attr_diamond = 144,
	attr_reputation = 145,
	attr_honor = 146,
	attr_beauty = 147,
	attr_intergration = 148,
	attr_stone_ex = 150,
	attr_enhance_ex = 151,
	attr_suit_ex = 152,
	attr_in_game = 165,
	attr_in_trade = 166,
	attr_in_game_time = 167,
	attr_out_game_time = 168,
	attr_ex_exp_time = 169,
	attr_evaluate_grade = 170,
	attr_arena_rank = 180,
	attr_arena_wincount = 181,
	attr_arena_buff = 182,
	attr_quest_remain_cnt_money = 185,
	attr_quest_remain_cnt_honor = 186,
	attr_quest_remain_cnt_exp = 187,
	attr_quest_daily_id = 188,
	attr_aging_cnt = 199,
	playermax = 200,
	
	attr_horse_level = 201,             -- 坐骑等级,默认为0,坐骑功能开放时默认为1
	attr_horse_exp = 202,               -- 坐骑当前经验条

	attr_horse_equip1_level = 203,      -- 坐骑装备1的等级
	attr_horse_equip1_exp = 204,        -- 坐骑装备1的经验条

	attr_horse_equip2_level = 205,      -- 坐骑装备2的等级
	attr_horse_equip2_exp = 206,        -- 坐骑装备2的经验条

	attr_horse_equip3_level = 207,      -- 坐骑装备3的等级
	attr_horse_equip3_exp = 208,        -- 坐骑装备3的经验条

	attr_horse_equip4_level = 209,      -- 坐骑装备4的等级
	attr_horse_equip4_exp = 210,        -- 坐骑装备4的经验条
	
    attr_horse_ride_state = 211,        -- 骑马状态,0=未骑马,1=骑马
    attr_horse_appearance = 212,        -- 坐骑外观等级,0=跟随真实阶数,>0=指定外观阶数
	
	attr_player_cloth = 220,
	attr_player_weapon = 221,
	attr_player_wings = 222,
	attr_player_fashion = 223,
	attr_player_magic_weapon = 224,
	attr_player_yuanshen = 225,--元神外观
	attr_pet_on = 250,
	attr_pet_pick_state = 251,
	attr_pet_market = 252,
	attr_pet_max = 253,
	attr_pet_cnt = 254,
	attr_pet_pickex_state = 255,
	attr_market_state = 260,
	attr_market_max_cnt = 261,
	attr_market_pet_select = 262,
	attr_market_bag_slot = 263,
	attr_market_player_begin_time = 264,
	attr_honor_cur = 280,
	attr_honor_curmax = 281,
	attr_cur_skillid = 285,
	attr_cur_targetx = 286,
	attr_cur_targety = 287,
	attr_dog_max = 290,
	attr_dog_cnt = 291,
	attr_dog_mode = 292,
	attr_teamcall_cd = 300,
	attr_refuse_addfriend = 301,
	attr_refuse_trade = 302,
	attr_hideFashion = 310,
	attr_hideWeapon = 311,
	attr_usemedicine_cd = 320,
	attr_skill_on_data = 350,
	attr_dead_relive_cooldown = 355,
	attr_vip_level = 360,
	attr_foot_effect = 361,
	attr_has_headtitle = 370,
	attr_open_headtitle = 371,
	attr_combat_exdata_begin = 400,
	attr_combat_exdata_end = 430,
	attr_max_pet_lvl = 450,
	attr_stone_point = 451,
	attr_wing_lvl = 452,
	attr_gold_used = 453,
	attr_stone_point_next_update = 454,
	attr_no_allow_chat = 460,
	attr_last_chat_time = 461,
	attr_chat_ex_data = 462,
	attr_ns_reward_begin = 500,
	attr_ns_lvl_enough = 501,
	attr_ns_wing_enough = 502,
	attr_ns_cbd_enough_first = 503,
	attr_ns_pet_lvl_enough = 504,
	attr_ns_cbd_enough_second = 506,
	attr_ns_cbd_enough_third = 510,
	attr_ns_reward_end = 520,
	attr_guild_post = 560,
	attr_guild_contribution = 561,
	attr_leave_guild_time = 570,
	attr_mobai_multiple = 600,
	attr_caishenchuangguan_state = 601,
	attr_meinvhusong_mid = 602,
	attr_meinvhusong_remain = 604,
	attr_meinvhusong_monstergid = 605,
	attr_qifushu_blessvalue = 607,
	attr_qifushu_usecnt = 608,
	attr_treasure_randomseed = 610,
	attr_treasure_loot = 611,
	attr_hanghuihusong_mid = 615,
	attr_worldpray_cnt = 630,
	attr_event_in = 666,
	attr_gene_exp_jade = 700,
	attr_gene_loot_exp = 701,
	attr_gene_fire_exp = 702,
	attr_exp_jade_iid = 703,
	attr_exp_jade_pos = 704,
	attr_gene_money_cnt = 705,
	attr_zs_cl_damage = 710,
	attr_fs_cl_damage = 711,
	attr_ds_cl_damage = 712,
	attr_ds_poison = 713,
	attr_cl_speed = 714,
	attr_speed_gene_imm = 715,
	attr_visible_gene_imm = 716,
	attr_zs_jichu_percent = 720,
	attr_zs_jichu_exdamage = 721,
	attr_zs_Fire_relive = 722,
	attr_hide_attack = 723,
	attr_ds_ghost = 724,
	attr_attack_other_ex = 730,
	attr_last_chat_string = 730,
	attr_last_chat_partnerid = 731,
	attr_last_chat_cmp_amount = 732,
	attr_last_chat_same_amount = 733,
	attr_last_chat_period = 734,
	attr_last_chat_partner_amount = 735,
	attr_level_change_time = 736,
	attr_last_chat_type = 737,
	attr_last_chat_amount = 738,
	attr_lose_recover = 740,
	attr_recharge_money = 801,
	attr_recharge_gift = 802,
	attr_limit_time_gift = 803,
	attr_ns_fight_lvl_gift = 804,
	attr_ns_fight_pet_lvl_gift = 805,
	attr_ns_fight_stone_gift = 806,
	attr_ns_fight_lvl_canget = 807,
	attr_ns_fight_pet_lvl_canget = 808,
	attr_ns_fight_stone_canget = 809,
	attr_online_begin_time = 810,
	attr_online_save = 811,
	attr_ns_login_data = 820,
	attr_ns_is_login = 821,
	attr_gfmrdllb_times = 822,
	attr_xmfb_buff = 850,
	attr_recharge_gold = 900,
	attr_force_attack_tgt = 901,
	attr_create_time = 997,
	attr_player_acstate = 998,
	attr_player_end = 999,
	attr_item_start = 100,
	attr_item_count = 200,
	attr_item_last_owner = 201,
	attr_item_limit_pick = 202,
	attr_item_type = 256,
	attr_item_cate = 257,
	attr_item_props_begin = 300,
	attr_item_props_end = 400,
	attr_item_end = 999,
	attr_market_start = 1000,
	attr_market_begin_time = 1200,
	attr_market_end_time = 1201,
	attr_market_max_slot = 1202,
	attr_market_sell_money = 1250,
	attr_market_sell_gold = 1251,
	attr_market_ishigh = 1260,
	attr_market_end = 2000,
	attr_monster_start = 100,
	attr_m_time_to_own = 101,
	attr_m_last_patrol_x = 210,
	attr_m_last_patrol_y = 211,
	attr_m_center_x = 220,
	attr_m_center_y = 221,
	attr_m_range = 222,
	attr_m_reward_exp = 230,
	attr_m_reward_id = 231,
	attr_m_default_skill = 310,
	attr_m_default_skill_distance = 311,
	attr_m_has_skill = 350,
	attr_m_has_event = 351,
	attr_m_search_range = 355,
	attr_m_next_cast_skill = 400,
	attr_m_next_cast_skill_distance = 401,
	attr_m_next_selected_skill = 402,
	attr_m_next_selected_skill_cd = 403,
	attr_m_next_selected_skill_times = 404,
	attr_m_next_skill_cast_failed_times = 405,
	attr_m_skill_dydata_begin = 500,
	attr_m_skill_dydata_end = 520,
	attr_m_boss_wid = 550,
	attr_m_owner_pid = 551,
	attr_m_is_plant = 560,
	attr_m_is_boss = 561,
	attr_skill_damage = 710,
	attr_monster_end = 999,
	attr_monster_generator_start = 100,
	attr_mg_refresh_interval = 200,
	attr_mg_refresh_range = 201,
	attr_mg_refresh_wave = 204,
	attr_mg_refresh_type = 205,
	attr_mg_monster_type_cnt = 206,
	attr_mg_endless_state = 207,
	attr_mg_refresh_sid_begin = 230,
	attr_mg_refresh_sid_end = 250,
	attr_mg_refresh_count_begin = 250,
	attr_mg_refresh_count_end = 270,
	attr_mg_refresh_limit_begin = 270,
	attr_mg_refresh_limit_end = 290,
	attr_mg_around_player_cnt = 330,
	attr_monster_generator_end = 999,
	attr_skill_start = 100,
	attr_s_script_duration = 201,
	attr_s_need_sync = 202,
	attr_s_process_class = 203,
	attr_s_group_id = 204,
	attr_s_sync_act = 205,
	attr_s_ignore_block = 207,
	attr_s_skill_ex_data = 220,
	attr_skill_end = 999,
	attr_pet_start = 100,
	attr_pet_combat_data_num = 117,
	attr_pet_state = 200,
	attr_pet_life_point = 202,
	attr_pet_ex_prop_type = 203,
	attr_pet_ex_prop_one = 204,
	attr_pet_ex_prop_two = 205,
	attr_pet_ex_prop_three = 206,
	attr_pet_top_prop_type = 207,
	attr_pet_top_prop = 208,
	attr_pet_reach_ten = 209,
	attr_pet_market_time = 310,
	attr_pet_offline_time = 311,
	attr_pet_speed = 430,
	attr_pet_character_begin = 440,
	attr_pet_character_end = 442,
	attr_pet_reborn_gobbleuplv_begin = 500,
	attr_pet_reborn_gobbleuplv_1 = 501,
	attr_pet_reborn_gobbleuplv_2 = 502,
	attr_pet_reborn_gobbleuplv_3 = 503,
	attr_pet_reborn_gobbleuplv_4 = 504,
	attr_pet_reborn_gobbleuplv_5 = 505,
	attr_pet_reborn_gobbleuplv_6 = 506,
	attr_pet_reborn_gobbleuplv_7 = 507,
	attr_pet_reborn_gobbleuplv_8 = 508,
	attr_pet_reborn_gobbleuplv_9 = 509,
	attr_pet_reborn_gobbleuplv_10 = 510,
	attr_pet_reborn_gobbleuplv_end = 511,
	attr_pet_reborn_cnt = 551,
	attr_pet_end = 999,
	gst_Invalid = 0,
	gst_Idle = 1,
	gst_Dead = 2,
	gst_Backing = 3,
	gst_Tracking = 4,
	gst_Runaway = 5,
	gst_Attacking = 6,
	gst_Following = 7,
	gst_Protected = 8,
	gst_Mine = 9,
	gst_Trade = 10,
	gst_Offline = 11,
	gst_Max = 12,
	emm_Aggressive = 0,
	emm_Passive = 1,
	emm_Runaway = 2,
	emm_Static = 3,
	emm_Hold = 4,
	emm_Mercs = 5,
	emm_Guard = 6,
	emm_Following = 7,
	emm_Marching = 8,
	emm_MarchingAggressive = 9,
	emm_SelfDestroy = 10,
	emm_SelfDestroyAggressive = 11,
	emm_Sentry = 12,
	emm_SentryMove = 13,
	emm_Totem = 14,
	emm_GirlMove = 15,
	emm_SentryHunting = 16,
	epetm_Normal = 0,
	epetm_InMarket = 1,
	epetm_InMarket_Offline = 2,
	attr_npc_getexdata = 300,
	attr_npc_cloth = 301,
	attr_npc_weapon = 302,
	attr_npc_wings = 303,
	attr_npc_pid = 304,
	attr_npc_gender = 305,
	attr_npc_rebornlevel = 306,
	attr_npc_job = 307,
	attr_npc_record_str = 400,
	eot_None = 0,
	eot_SinglePlayer = 1,
	eot_Team = 2,
	eot_Guild = 3,
	eot_Faction = 4,
}


--
--	for table : EntityRevive
--
EntityRevive = {
	revive_dead = 1,
	revive_safe = 2,
}


--
--	for table : Pkstate
--
Pkstate = {
	pks_white = 0,
	pks_yellow = 1,
	pks_gray = 2,
	pks_red = 3,
	pks_clean = 4,
}


--
--	for table : Effect
--
Effect = {
	effect_visable = 0,
	effect_posion_red = 1,
	effect_posion_green = 2,
	effect_mitigate = 3,
	effect_speed_down = 4,
	effect_speed_up = 5,
	effect_violent = 6,
	effect_offline = 7,
	effect_daze = 8,
	effect_hide = 9,
	effect_firereborn = 10,
	effect_be_attacking = 11,
	effect_freezon_ice = 12,
}


--
--	for table : SceneProp
--
SceneProp = {
	prop_size_x = 1,
	prop_size_y = 2,
	prop_block_player = 3,
	prop_pk_drop = 4,
	prop_relive_type = 5,
	prop_pk_red = 6,
	prop_scene_close = 20,
	prop_scene_close_type = 21,
	prop_scene_close_id = 22,
	prop_scene_close_posx = 23,
	prop_scene_close_posy = 24,
	prop_next_scene = 50,
	prop_instance_type = 51,
	prop_instance_oid = 52,
	prop_instance_begin_sid = 53,
	prop_instance_portal = 55,
	prop_scene_allow_kill = 60,
	prop_scene_enter_disable = 70,
	prop_scene_skill_limit = 71,
	prop_scene_pet_limit_in = 72,
	prop_scene_dog_limit_in = 73,
	prop_scene_area_id = 200,
	scene_time_end = 1201,
	-- 怪物攻城相关属性
	siege_active = 1202,
	siege_wave = 1203,
	siege_start_time = 1204,
	siege_monster_count = 1205,
	siege_last_9pm_hour = 1206,
	siege_last_9pm_minute = 1207,
	siege_trigger_guild = 1208,
	
	-- PK场
	pkc_team_a = 3000,
	pkc_team_b = 3001,
	
	-- 四季轮回镜属性
	sj_boss1 = 3010,
	sj_boss2 = 3011,
	sj_boss3 = 3012,
	sj_boss4 = 3013,
	sj_alive = 3014,
	
	-- 五行试炼阵属性
	wx_boss1 = 3015,
	wx_boss2 = 3016,
	wx_boss3 = 3017,
	wx_boss4 = 3018,
	wx_boss5 = 3019,
	wx_alive = 3020,
	wx_step = 3021,
	
	-- 渡劫副本属性
	djfb_boss1 = 3022,
	djfb_boss2 = 3023,
	djfb_boss3 = 3024,
	djfb_boss4 = 3025,
	djfb_alive = 3026,
	
	--冰与火
    coop_boss = 3040,           -- BOSS的实体ID
    coop_need_pos = 3045,       -- 需要站位的位置
    coop_timer = 3046,          -- 位置更换计时器
    coop_player_count = 3048,   -- 玩家数量
    coop_boss_active = 3052,    -- BOSS是否激活
    coop_check_counter = 3053,  -- 检查计数器
    coop_challenge_started = 3054,  -- 挑战是否已开始
    coop_position_markers = 3055, -- 站位点标记物ID列表
    coop_map_loaded = 3056,      -- 地图加载标记
	
    
	--情侣望月岛属性
	ql_boss1 = 3057,
	ql_boss2 = 3058,
	ql_boss3 = 3059,
	ql_boss4 = 3060,
	ql_alive = 3061
}


--
--	for table : WorldProp
--
WorldProp = {
	prop_activity_begin = 0,
	prop_player_limit = 1,
	prop_client_gm_state = 2,
	prop_world_player = 3,
	prop_world_chat_req = 4,
	prop_activity_end = 400,
	prop_world_monster_begin = 500,
	prop_world_monster_end = 699,
	prop_mb_data = 800,
	prop_mb_player = 801,
	prop_first_zs_app = 810,
	prop_first_fs_app = 811,
	prop_first_ds_app = 812,
	prop_first_zs_data = 813,
	prop_first_fs_data = 814,
	prop_first_ds_data = 815,
	prop_gcz_data = 820,
	prop_gcz_kill_most = 821,
	prop_gcz_job_master = 830,
	prop_gcz_job_deputy = 831,
	prop_gcz_job_general = 832,
	prop_gcz_job_decree = 833,
	prop_gcz_job_manager = 834,
	prop_arena_first_lvl = 855,
	prop_arena_first_pid = 860,
	prop_arena_second_pid = 861,
	prop_arena_third_pid = 862,
	prop_first_other_zs_app = 870,
	prop_first_other_fs_app = 871,
	prop_first_other_ds_app = 872,
	prop_first_other_zs_data = 873,
	prop_first_other_fs_data = 874,
	prop_first_other_ds_data = 875,
	prop_new_server_begin = 880,
	prop_new_server_lvl_zs = 881,
	prop_new_server_lvl_fs = 882,
	prop_new_server_lvl_ds = 883,
	prop_server_first_zs = 884,
	prop_server_first_fs = 885,
	prop_server_first_ds = 886,
	city_master_guild = 1000,
	city_master_player = 1001,
	city_own4days_reward = 1002,
	cross_server_guild = 1003,
	cross_win_guild = 1004,
	prop_new_server_end = 1150,
	prop_ns_fight_lvl_1 = 1151,
	prop_ns_fight_lvl_2 = 1152,
	prop_ns_fight_lvl_3 = 1153,
	prop_ns_fight_lvl_4 = 1154,
	prop_ns_fight_lvl_5 = 1155,
	prop_ns_fight_pet_lvl_1 = 1160,
	prop_ns_fight_pet_lvl_2 = 1161,
	prop_ns_fight_pet_lvl_3 = 1162,
	prop_ns_fight_pet_lvl_4 = 1163,
	prop_ns_fight_pet_lvl_5 = 1164,
	prop_ns_fight_stone_1 = 1171,
	prop_ns_fight_stone_2 = 1172,
	prop_ns_fight_stone_3 = 1173,
	prop_ns_fight_stone_4 = 1174,
	prop_ns_fight_stone_5 = 1175,
	prop_pray_first = 1180,
	prop_world_begin_time = 2000,
	prop_world_newserverbegin = 5000,
	prop_world_first_zs_lvl = 5001,
	prop_world_first_fs_lvl = 5002,
	prop_world_first_ds_lvl = 5003,
	prop_world_wings_max = 5004,
	prop_world_first_city_master = 5005,
	prop_world_pet_max = 5006,
	prop_world_tuhao_max = 5007,
	prop_world_stone_max = 5008,
	prop_world_sprider_max = 5009,
	prop_world_strong_max = 5010,
	prop_world_identify_max = 5011,
	prop_world_first_cbt_zs_max = 5012,
	prop_world_first_cbt_fs_max = 5013,
	prop_world_first_cbt_ds_max = 5014,
	prop_world_newserverend = 5100,
	shou_chong_li_bao = 20101,
	mei_ri_shou_chong = 20102,
	lei_ji_chong_zhi = 20103,
	zai_xian_jiang_li = 20104,
	dan_bi_chong_zhi = 20105,
	pan_long_bao_xiang = 20106,
	kai_fu_huo_dong = 20201,
	li_bao_feng_shang = 20202,
	jv_bao_pen = 20203,
	kai_fu_jing_ji = 20301,
	he_fu_hui_kui = 20401,
	huo_dong_shang_dian = 20402,
	dui_huan_shang_dian = 20403,
	mei_ri_hui_kui = 20404,
	qiang_hua_hui_kui = 20405,
	chong_wu_hui_kui = 20406,
	hun_shi_hui_kui = 20407,
	chi_bang_hui_kui = 20408,
	xun_bao_hui_kui = 20409,
	shi_zhuang_hui_kui = 20410,
	huan_wu_hui_kui = 20411,
	yuan_bao_hui_kui = 20412,
	xing_yun_zhuan_pan = 20417,
	he_fu_lei_ji_chong_zhi = 20413,
	he_fu_chong_fu_chong_zhi = 20414,
	he_fu_dan_bi_chong_zhi = 20415,
	he_fu_shou_ci_chong_zhi = 20416,
	ma_shang_qiang_gou = 20418,
	feng_kuang_qiang_gou = 20419,
	kua_fu_pai_hang_bang = 20420,
}


--
--	for table : CtrlData
--
CtrlData = {
	shou_chong_li_bao = 20101,
	mei_ri_shou_chong = 20102,
	lei_ji_chong_zhi = 20103,
	zai_xian_jiang_li = 20104,
	dan_bi_chong_zhi = 20105,
	pan_long_bao_xiang = 20106,
	kai_fu_huo_dong = 20201,
	li_bao_feng_shang = 20202,
	jv_bao_pen = 20203,
	kai_fu_jing_ji = 20301,
	he_fu_hui_kui = 20401,
	huo_dong_shang_dian = 20402,
	dui_huan_shang_dian = 20403,
	mei_ri_hui_kui = 20404,
	qiang_hua_hui_kui = 20405,
	chong_wu_hui_kui = 20406,
	hun_shi_hui_kui = 20407,
	chi_bang_hui_kui = 20408,
	xun_bao_hui_kui = 20409,
	shi_zhuang_hui_kui = 20410,
	huan_wu_hui_kui = 20411,
	yuan_bao_hui_kui = 20412,
	xing_yun_zhuan_pan = 20417,
	he_fu_lei_ji_chong_zhi = 20413,
	he_fu_chong_fu_chong_zhi = 20414,
	he_fu_dan_bi_chong_zhi = 20415,
	he_fu_shou_ci_chong_zhi = 20416,
	ma_shang_qiang_gou = 20418,
	feng_kuang_qiang_gou = 20419,
	kua_fu_pai_hang_bang = 20420,
}


--
--	for table : WorldBlob
--
WorldBlob = {
	blob_treasurehunt_record = 700,
	blob_arena_record = 701,
	blob_arenareward = 749,
	blob_arena = 750,
	blob_applyGcz = 751,
	blob_last_applyGcz = 752,
	blob_chartlistbegin = 800,
	blob_combadata = 801,
	blob_zs_cbt = 802,
	blob_fs_cbt = 803,
	blob_ds_cbt = 804,
	blob_leveldata = 810,
	blob_zs_level = 811,
	blob_fs_level = 812,
	blob_ds_level = 813,
	blob_money_top = 830,
	blob_pet_top = 840,
	blob_guildlevel_top = 850,
	blob_guildylt_top = 851,
	blob_fireworks_data = 861,
	blob_chartlistend = 1000,
}


--
--	for table : GuildProp
--
GuildProp = {
	guild_contribution = 1,
	guild_money = 2,
	guild_masterid = 3,
	guild_rank = 5,
	guild_building_id = 15,
	guild_building_build_time = 16,
	guild_building_id_begin = 17,
	guild_level = 17,
	guild_building_gong_dian_level = 17,
	guild_building_guan_gong_level = 18,
	guild_building_fu_li_level = 19,
	guild_building_mao_xian_level = 20,
	guild_building_shen_shou_level = 21,
	guild_building_shang_dian_level = 22,
	guild_building_guang_huan_level = 23,
	guild_building_id_end = 50,
	guild_apply_gcz = 70,
	guild_open_gcz_buff = 71,
	guild_private_notice = 1,
	guild_public_notice = 2,
	guild_mastername = 3,
	guild_nick_normal = 10,
	guild_nick_master = 11,
	guild_nick_second = 12,
	guild_nick_elite = 13,
	post_normal = 0,
	post_master = 1,
	post_second_master = 2,
	post_elite = 3,
}


--
--	for table : ItemProp
--
ItemProp = {
	Item_EnhanceLevel = 1,
	Item_DataCombo = 2,
	Item_DataX = 3,
	Item_DataY = 4,
	Item_DataZ = 5,
	Item_SpecialIdx = 6,
	Item_SpecialData = 7,
	Item_MagicWeaponID = 8,
	Item_RebornLvl = 9,
	Item_EquipMax = 10,
	Item_Link_Pet = 11,
	Item_Market_Type = 12,
	Item_Market_Price = 13,
	Item_Lucky = 14,
	Item_ExpStore = 15,
	Item_Durable = 16,
	Item_Polish = 17,
	Item_Bind = 18,
	Item_FootPolish = 19,
	Item_QLPolish = 20,
	Item_GetTime = 21,
	Item_EquipLock = 22,
	Item_FuMoPropID     = 23,   -- 附魔获得的属性的ID
	Item_FuMoPropValue	= 24,   -- 附魔获得的属性的值
	Item_FuMoEnhanceCount	= 25,   -- 附魔次数
	Item_EvaluateCount  = 26,   -- 装备鉴定次数
	Item_EnhanceFailCount = 27,   --翅膀羽化失败次数
	Item_Max			= 28,


	Bag_Invalid = -1,
	Bag_Role = 0,
	Bag_Player = 1,
	Bag_Pet = 2,
	Bag_Warehouse = 3,
	Bag_Market = 4,
	Bag_Trade = 5,
	Bag_NPC = 6,
	Bag_All = 10,
	Bag_Player_All = 11,
	Bag_Hollow = 12,
	ItemPosition_Null = 0,
	ItemPosition_Equip_Neckless = -1,
	ItemPosition_Equip_Weapon = -2,
	ItemPosition_Equip_Weapon_Two = -3,
	ItemPosition_Equip_Bangle = -4,
	ItemPosition_Equip_Ring = -5,
	ItemPosition_Equip_Stone = -6,
	ItemPosition_Equip_Fashion = -7,
	ItemPosition_Equip_Wings = -8,
	ItemPosition_Equip_Belt = -9,
	ItemPosition_Equip_Shoes = -10,
	ItemPosition_Equip_Ring_Two = -11,
	ItemPosition_Equip_Bangle_Two = -12,
	ItemPosition_Equip_Cloth = -13,
	ItemPosition_Equip_Medal = -14,
	ItemPosition_Equip_Helmet = -15,
	ItemPosition_Equip_Material = -16,
	ItemPosition_Equip_Foot = -17,
	ItemPosition_Equip_Yuanshen			= -18,	-- 元神
	ItemPosition_Equip_Shenqi1			= -19,	-- 法器
	ItemPosition_Equip_Shenqi2			= -20,	-- 斗笠
	ItemPosition_Equip_Shenqi3			= -21,	-- 肩铠
	ItemPosition_Equip_Shenqi4			= -22,	-- 护手
	ItemPosition_Equip_Shenqi5			= -23,	-- 法袍
	ItemPosition_Equip_Shenqi6			= -24,	-- 护腿
	ItemPosition_Equip_Max		= -25,
	ItemPosition_stone_begin = -99,
	Neckless_begin = -100,
	Weapon_begin = -105,
	Weapon_Two_begin = -110,
	Bangle_begin = -115,
	Ring_begin = -120,
	Stone_begin = -125,
	Fashion_begin = -130,
	Wings_begin = -135,
	Belt_begin = -140,
	Shoes_begin = -145,
	Ring_Two_begin = -150,
	Bangle_Two_begin = -155,
	Cloth_begin = -160,
	Medal_begin = -165,
	Helmet_begin = -170,
	Material_begin = -175,
	ItemPosition_stone_end = -180,
	ItemPosition_ScopeForRole = 16,
	ItemDurable_Weapon = 1,
	ItemDurable_Equip = 2,
	ItemDurable_Repair = 3,
	ItemRepair_Money = 1,
	ItemRepair_Item = 2,
	ItemPosition_stone_end = 0,
	ItemPosition_Null = -1,
	Player_Bag_Start = 1,
	Player_Bag_End = 150,
	Pet_Bag_Start = 151,
	Pet_Bag_End = 300,
	Treasure_Warehouse_Start = 301,
	Treasure_Warehouse_End = 660,
	Market_Bag_Start = 661,
	Market_Bag_End = 700,
	NPC_Bag_Start = 701,
	NPC_Bag_End = 820,
	Trade_Bag_Start = 821,
	Trade_Bag_End = 833,
	Hollow_Bag_Start = 834,
	Hollow_Bag_End = 900,
	BagSlotEnd = 901,
	Item_No_Bind = 0,
	Item_Has_bind = 1,
	Item_PutOn_Bind = 1,
	Item_Must_bind = 2,
	Item_Cant_bind = 3,
}


--
--	for table : GiftProp
--
GiftProp = {
	gift_recharge_all = 1,
	gift_limittime = 2,
	gift_recharge_day = 3,
	gift_recharge_month = 4,
	gift_online = 5,
	gift_sign_up = 6,
	gift_week = 7,
	gift_ns_lvlup = 8,
	gift_ns_petlvlup = 9,
	gift_ns_stonep = 10,
}


--
--	for table : EventProp
--
EventProp = {
	GT_Invalid = 0,
	GT_Quest = 1,
	GT_Combat = 2,
	GT_PlayerLoad = 4,
	GT_Entity = 8,
	GT_Script = 32768,
	EID_KillMonster = 1,
	EID_TalkNPC = 2,
	EID_TAKEITEM = 3,
	EID_FinishQuest = 4,
	EID_GoToInstance = 5,
	EID_Attack = 300,
	EID_Be_Attacked = 301,
	EID_Be_Collided = 302,
	EID_Be_Poison = 303,
	EID_Fly = 304,
	EID_EffectRmv = 305,
	EID_MeetEntityS = 350,
	EID_LeaveEntityS = 351,
	EID_Init = 360,
	EID_PLoadBegin = 150,
	EID_ExData = 151,
	EID_Item = 152,
	EID_Quest = 153,
	EID_Skill = 154,
	EID_Pet = 155,
	EID_EventData = 156,
	EID_RelationData = 157,
	EID_PLoadEnd = 158,
	EID_Null = 200,
	EID_Killexp = 201,
	EID_Questexp = 202,
	EID_Fireexp = 203,
	EID_GuildFightexp = 204,
	EID_SceneGetInfo = 800,
	EID_MarketBuy = 801,
}


--
--	for table : CombatProp
--
CombatProp = {
	batt_miss = 0,
	batt_immunity = 1,
	batt_hpchange = 2,
}


--
--	for table : ChatProp
--
ChatProp = {
	type_system = 1,
	type_world = 2,
	type_nearby = 3,
	type_group = 4,
	type_guild = 5,
	type_private = 6,
	type_horn = 7,
	type_gm = 8,
}


--
--	for table : VIPProp
--
VIPProp = {
	vip_attradd = 1,
	vip_registerexcnt = 2,
	vip_godwelfareexcnt = 3,
	vip_autoregiste = 4,
	vip_registeex = 5,
	vip_killmonster = 6,
	vip_shoescnt = 7,
	vip_warehouseadd = 8,
	vip_sportscd = 9,
	vip_moneyquest = 10,
	vip_honorquest = 11,
	vip_expquest = 12,
	vip_escortbelle = 13,
	vip_onkeypetlvlup = 14,
	vip_praycnt = 15,
	vip_clearredname = 16,
}


-- 玩家性别枚举
enum_GenderType = {
	etgd_male	 = 1,
	etgd_female	 = 2,
}


-- 行会封号
enum_GuildPost ={
	post_normal	 = 0,			-- 普通成员
	post_master  = 1,			-- 会长
	post_second_master = 2,		-- 副会长
	post_elite = 3,				-- 精英
}


-- 背包类型
enum_BagType = {
	Bag_Invalid	= -1,
	Bag_Role	= 0,
	Bag_Player	= 1,		-- 玩家背包
	Bag_Pet		= 2,		-- 宠物背包
	Bag_Warehouse	= 3,	-- 仓库
	Bag_Market	= 4,		-- 摊位
	Bag_Trade	= 5,		-- 交易
	Bag_NPC	= 6,			-- ?
	Bag_All	= 10,
	Bag_Player_All	= 11,	-- position > 0 && position < petbag_end
	Bag_Hollow = 12,
}

-- 道具装备位
ItemPosition = {
	-- 角色身上的装备位
	ItemPosition_Null				= 0,	-- 常用的无效装备位
	ItemPosition_Equip_Neckless     = -1,	-- 项链
	ItemPosition_Equip_Weapon		= -2,	-- 武器
	ItemPosition_Equip_Weapon_Two	= -3,	-- 幻武
	ItemPosition_Equip_Bangle		= -4,	-- 手镯1
	ItemPosition_Equip_Ring		    = -5,	-- 戒指1
	ItemPosition_Equip_Stone		= -6,	-- 宝石
	ItemPosition_Equip_Fashion		= -7,	-- 时装
	ItemPosition_Equip_Wings		= -8,	-- 翅膀
	ItemPosition_Equip_Belt			= -9,	-- 腰带
	ItemPosition_Equip_Shoes		= -10,	-- 鞋子
	ItemPosition_Equip_Ring_Two		= -11,	-- 戒指2
	ItemPosition_Equip_Bangle_Two	= -12,	-- 手镯2
	ItemPosition_Equip_Cloth		= -13,	-- 衣服
	ItemPosition_Equip_Medal		= -14,	-- 勋章
	ItemPosition_Equip_Helmet		= -15,	-- 头盔
	ItemPosition_Equip_Material		= -16,	-- 法球
	ItemPosition_Equip_Foot			= -17,	-- 足迹
	ItemPosition_Equip_Yuanshen		= -18,	-- 元神
	ItemPosition_Equip_Shenqi1		= -19,	-- 法器
	ItemPosition_Equip_Shenqi2		= -20,	-- 斗笠
	ItemPosition_Equip_Shenqi3		= -21,	-- 肩铠
	ItemPosition_Equip_Shenqi4		= -22,	-- 护手
	ItemPosition_Equip_Shenqi5		= -23,	-- 法袍
	ItemPosition_Equip_Shenqi6		= -24,	-- 护腿
	ItemPosition_Equip_Max		= -25,
}

-- 物品类型
ItemType =
{
	ItemType_Null	=	0,

	ItemType_Equip_Start			= 0,
	ItemType_Equip_Weapon			= 1,	--  武器
	ItemType_Equip_Helmet			= 2,	--	头盔
	ItemType_Equip_Neckless			= 3,	--	项链
	ItemType_Equip_Ring				= 4,	--	戒指
	ItemType_Equip_Medal			= 5,	--	勋章

	ItemType_Equip_Cloth			= 6,	--	衣服
	ItemType_Equip_Shoes			= 7,	--	鞋子
	ItemType_Equip_Belt				= 8,	--	腰带
	ItemType_Equip_Bangle			= 9,	--	手镯
	ItemType_Equip_Stone			= 10,	--	宝石
	ItemType_Equip_Wings			= 11,	--	翅膀
	ItemType_Equip_Fashion			= 12,	--	时装

	ItemType_Equip_Magic_Weapon		= 13,	--  幻武
	ItemType_Equip_Material			= 14,	--  法球
	ItemType_Equip_Foot				= 15,	--  足迹
	ItemType_Equip_Yuanshen         = 16,	--  元神
	ItemType_Equip_Shenqi1          = 17,	--  法器
	ItemType_Equip_Shenqi2          = 18,	--  斗笠
	ItemType_Equip_Shenqi3          = 19,	--  肩铠
	ItemType_Equip_Shenqi4          = 20,	--  护手
	ItemType_Equip_Shenqi5          = 21,	--  法袍
	ItemType_Equip_Shenqi6          = 22,	--  护腿

	ItemType_Equip_End				,


	ItemType_Stone_Vit				=	1,	--
	ItemType_Stone_Str				=	2,	-- 力量
	ItemType_Stone_Agi				=	3,	-- 敏捷
	ItemType_Stone_Int				=	4,	-- 魔防魂石

	ItemType_Stone_PAttack			=	5,	--
	ItemType_Stone_PDefense			=	6,
	ItemType_Stone_MAttack			=	7,
	ItemType_Stone_MDefense			=	8,

	ItemType_Stone_Hit				=	9,
	ItemType_Stone_Dodge			=	10,

	ItemType_Stone_Critical			=	11,
	ItemType_Stone_Resist			=	12,

	ItemType_Stone_Break			=	13,
	ItemType_Stone_Block			=	14,

	ItemType_Stone_Morale			=	15,
	ItemType_Stone_Speed			=	16,

	ItemType_Stone_Max,

	ItemType_Pet					=  1,	-- 宠物
--	ItemType_Potion					=  2,
	ItemType_ExpJade				=  3,	-- 经验玉
	ItemType_Book					=  4,	-- 技能书
	ItemType_ComfirmBuy				=  5,	-- ?通行证
	ItemType_FastSettting			=  6,
	ItemType_Other_Max,
};


-- 场景ID
EnumSceneID =
{
	WangCheng = 2,	-- 王城
}



-- 坐骑装备ID到对应的属性ID
TableHorseEquipIDToAttrID = {
	[1] = {EquipID = 1, Level = EntityProp.attr_horse_equip1_level, Exp = EntityProp.attr_horse_equip1_exp},
	[2] = {EquipID = 2, Level = EntityProp.attr_horse_equip2_level, Exp = EntityProp.attr_horse_equip2_exp},
	[3] = {EquipID = 3, Level = EntityProp.attr_horse_equip3_level, Exp = EntityProp.attr_horse_equip3_exp},
	[4] = {EquipID = 4, Level = EntityProp.attr_horse_equip4_level, Exp = EntityProp.attr_horse_equip4_exp},
}
